// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "@storyblok/react"

export interface CategoriesStoryblok {
  label?: string
  component: "categories"
  _uid: string
  [k: string]: any
}
export interface AllCategoriesStoryblok {
  component: "allCategories"
  _uid: string
  [k: string]: any
}

export interface AllEventsSectionStoryblok {
  title?: string
  events?: (ISbStoryData<EventStoryblok> | string)[]
  categories?: (ISbStoryData<CategoriesStoryblok> | string)[]
  component: "allEventsSection"
  _uid: string
  [k: string]: any
}

export interface ButtonStoryblok {
  label?: string
  link?: string
  variant?: ("" | "primary" | "secondary")[]
  component: "button"
  _uid: string
  [k: string]: any
}

export interface AssetStoryblok {
  alt?: string
  copyright?: string
  id: number
  filename: string
  name: string
  title?: string
  focus?: string
  [k: string]: any
}

export interface CarouselItemStoryblok {
  title?: string
  subtitle?: string
  image?: AssetStoryblok
  ctas?: ButtonStoryblok[]
  component: "carouselItem"
  _uid: string
  [k: string]: any
}

export interface CarouselSectionStoryblok {
  title?: string
  subtitle?: string
  carouselItems?: CarouselItemStoryblok[]
  component: "carouselSection"
  _uid: string
  [k: string]: any
}

export interface CategoryStoryblok {
  label?: string
  component: "category"
  _uid: string
  [k: string]: any
}

export interface RichtextStoryblok {
  type: string
  content?: RichtextStoryblok[]
  marks?: RichtextStoryblok[]
  attrs?: any
  text?: string
  [k: string]: any
}

export type MultilinkStoryblok =
  | {
      id?: string
      cached_url?: string
      anchor?: string
      linktype?: "story"
      target?: "_self" | "_blank"
      story?: {
        name: string
        created_at?: string
        published_at?: string
        id: number
        uuid: string
        content?: {
          [k: string]: any
        }
        slug: string
        full_slug: string
        sort_by_date?: null | string
        position?: number
        tag_list?: string[]
        is_startpage?: boolean
        parent_id?: null | number
        meta_data?: null | {
          [k: string]: any
        }
        group_id?: string
        first_published_at?: string
        release_id?: null | number
        lang?: string
        path?: null | string
        alternates?: any[]
        default_full_slug?: null | string
        translated_slugs?: null | any[]
        [k: string]: any
      }
      [k: string]: any
    }
  | {
      url?: string
      cached_url?: string
      anchor?: string
      linktype?: "asset" | "url"
      target?: "_self" | "_blank"
      [k: string]: any
    }
  | {
      email?: string
      linktype?: "email"
      target?: "_self" | "_blank"
      [k: string]: any
    }

export interface ContentLinkSectionStoryblok {
  title?: string
  body?: RichtextStoryblok
  link?: Exclude<
    MultilinkStoryblok,
    { linktype?: "email" } | { linktype?: "asset" }
  >
  image?: AssetStoryblok
  component: "contentLinkSection"
  _uid: string
  [k: string]: any
}

export interface ContentSectionStoryblok {
  title?: string
  image?: AssetStoryblok
  cta?: ButtonStoryblok[]
  body?: RichtextStoryblok
  component: "contentSection"
  _uid: string
  [k: string]: any
}

export interface EventStoryblok {
  title?: string
  image?: AssetStoryblok
  preview?: RichtextStoryblok
  description?: RichtextStoryblok
  price?: string
  location?: string
  datetime?: string
  category?: (ISbStoryData<CategoriesStoryblok> | string)[]
  component: "event"
  _uid: string
  [k: string]: any
}

export interface HeroSectionStoryblok {
  header?: string
  subheader?: string
  heroImage?: AssetStoryblok
  cta?: EventStoryblok[]
  component: "heroSection"
  _uid: string
  [k: string]: any
}

export interface PageStoryblok {
  body?: (
    | AllCategoriesStoryblok
    | AllEventsSectionStoryblok
    | ButtonStoryblok
    | CarouselItemStoryblok
    | CarouselSectionStoryblok
    | CategoryStoryblok
    | ContentLinkSectionStoryblok
    | ContentSectionStoryblok
    | EventStoryblok
    | HeroSectionStoryblok
    | PageStoryblok
  )[]
  component: "page"
  _uid: string
  [k: string]: any
}
