#!/bin/bash

echo "🏗️👷 Running static checks before committing"
npx lint-staged || (echo "❌ Failed static checks. Make the changes required above." && exit 1)
echo "✅ Code passes static checks, committing to local."

